[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tauri = { version = "1.6.0", features = [ "shell-all", "http-all", "fs-read-file", "fs-write-file", "dialog-open", "fs-remove-file", "window-print", "path-all", "window-start-dragging", "window-close", "window-minimize"] }
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0.114"
zip-extract = "0.1.3"
scraper = "0.19.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
